name: micro_app_http
description: A Flutter package using DIO to make HTTP requests abstracts.
version: 0.0.1
homepage: https://joaopedromartins.com.br/flutter/packages/micro_app_http

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
